### ISSUE TITLE
GPA_BeginSample doc is talking about GPA_GetSampleResult instead

### ISSUE THREAD

**Issue by Dragon31337** [GPUOpen-Tools/gpu_performance_api#56]
see https://gpuperfapi.readthedocs.io/en/latest/api_functions/gpa_getsampleresult.html?highlight=GPA_BeginSample
to find out that it's about GPA_GetSampleResult

**Comment by PLohrmannAMD** [comment]
Thank you for reporting this!

**Comment by PLohrmannAMD** [comment]
This was resolved as part of the GPUPerfAPI 3.8 release.
