### ISSUE TITLE
6700XT not supported?

### ISSUE THREAD

**Issue by weirdmadhat** [GPUOpen-Tools/gpu_performance_api#57]
I get GPA_STATUS_ERROR_HARDWARE_NOT_SUPPORTED when I try open new GPU context

**Comment by PLohrmannAMD** [comment]
Thank you for the report!

Can you confirm that you're using the latest 3.9.0.13 binaries?
Which graphics API and OS are you using?
What are the Device ID and Revision ID of your card?

According to https://github.com/GPUOpen-Tools/common_src_device_info/blob/master/DeviceInfo.cpp GPA is supporting Device ID **0x73DF** and Revision IDs (**0xC0**, **0xC1**, and **0xC5**) with that name.

**Comment by eelliott-amd** [comment]
Closing this issue as completed as continued testing has shown that the Radeon RX 6700 XT is supported but please contact us if you continue experiencing issues!
