### ISSUE TITLE
Questions about functionality

### ISSUE THREAD

**Issue by qskgpro** [GPUOpen-Tools/gpu_performance_api#61]
您好，我想知道您的项目中是否有关于AMD的GPU超频相关的操作
Hello, I want to know if there are any operations related to AMD GPU overclocking in your project

或者说？设置显存，核心的频率，风扇的转速，功耗，显存电压等相关操作
Or? Set the video memory, core frequency, fan speed, power consumption, video memory voltage and other related operations

抱歉我都英语并不是很好，我是使用翻译工具来进行翻译的
Sorry, my English is not very good. I use translation tools to translate

**Comment by PLohrmannAMD** [comment]
Hello, No this API does not provide any interface for changing those operations.
